# compose 2 is enough for this file
version: '2'

services:
  simulator-build:
    image: microsoft/dotnet:2.0.3-sdk-jessie
    volumes:
      - .:/sources
    working_dir: /sources/MicroserviceArchitecture.Simulator
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o ./obj/Docker/publish"
    
  simulator-tests:
    image: microsoft/dotnet:2.0.3-sdk-jessie
    volumes:
      - .:/sources
    working_dir: /sources/MicroserviceArchitecture.Simulator.Tests
    
    # -fx-version is a fix for https://github.com/xunit/xunit/issues/1573
    command: /bin/bash -c "dotnet restore && dotnet xunit -trait Category=Unit --fx-version 2.0.3 -xml simulator-test-results.xml"
