apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.DeploymentName }}
  labels: 
    app: {{ .Values.DeploymentName }}
    team: {{ .Values.Team }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.DeploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.DeploymentName }}
    spec:
      containers:
      - name: msa-{{ .Values.DeploymentName }}
        image: {{ .Values.ImageRegistry }}/{{ .Values.DeploymentName }}:{{ .Values.ImageVersion }}
        imagePullPolicy: Always
        env:
          - name: AzureRegionTag
            valueFrom:
              configMapKeyRef:
                name: infrastructure-configmap
                key: AzureRegionTag
          - name: EnvironmentTag
            valueFrom:
              configMapKeyRef:
                name: infrastructure-configmap
                key: EnvironmentTag
          - name: StorageAccessKey
            valueFrom:
              secretKeyRef:
                name: infrastructure-secrets
                key: StorageAccessKey
          - name: EventHubListenConnectionString
            valueFrom:
              secretKeyRef:
                name: infrastructure-secrets
                key: EventHubListenConnectionString
        resources:
          requests:
            memory: "{{ .Values.RequestsMemory }}"
            cpu: "{{ .Values.RequestsCpu }}"
          limits:
            memory: "{{ .Values.LimitsMemory }}"
            cpu: "{{ .Values.LimitsCpu }}"