apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.DeploymentName }}
  labels:
    app: {{ .Values.DeploymentName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.ReplicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.DeploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.DeploymentName }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: tourmonitoring-{{ .Values.DeploymentName }}
        image: {{ .Values.DeploymentName }}:{{ .Values.ImageVersion }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{{ .Values.RequestsMemory }}"
            cpu: "{{ .Values.RequestsCpu }}"
          limits:
            memory: "{{ .Values.LimitsMemory }}"
            cpu: "{{ .Values.LimitsCpu }}"