kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.ServiceName }}
  labels:
    app: {{ .Values.DeploymentName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ .Values.DeploymentName }}
  ports:
  - protocol: TCP
    port: {{ .Values.ServicePort }}
    targetPort: {{ .Values.ServiceTargetPort }}