kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/port: "{{ .Values.MonitoringServicePort }}"
    prometheus.io/scrape: "true"
  name: {{ .Values.MonitoringServiceName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.DeploymentName }}
  ports:
  - protocol: TCP
    port: {{ .Values.MonitoringServicePort }}
    targetPort: {{ .Values.MonitoringServiceTargetPort }}