kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.DeploymentName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.DeploymentName }}
  ports:
  - protocol: TCP
    port: {{ .Values.ServicePort }}
    targetPort: {{ .Values.ServiceTargetPort }}